const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {DatabaseSync}=require('node:sqlite');
const PORT=process.env.PORT||3000, ROOT=path.join(__dirname,'..'), DB_PATH=path.join(__dirname,'data','daftari.db');
fs.mkdirSync(path.dirname(DB_PATH),{recursive:true}); const db=new DatabaseSync(DB_PATH);
db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS businesses(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,code TEXT UNIQUE NOT NULL,owner_id INTEGER,status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL DEFAULT(datetime('now')));
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,full_name TEXT NOT NULL,business_id INTEGER NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'saler',created_at TEXT NOT NULL DEFAULT(datetime('now')));
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT(datetime('now')));
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,business_id INTEGER NOT NULL,name TEXT NOT NULL,buy_price REAL NOT NULL,sell_price REAL NOT NULL,quantity INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT(datetime('now')));
CREATE TABLE IF NOT EXISTS sales(id INTEGER PRIMARY KEY AUTOINCREMENT,business_id INTEGER NOT NULL,product_id INTEGER NOT NULL,product_name TEXT NOT NULL,quantity INTEGER NOT NULL,sell_price REAL NOT NULL,buy_price REAL NOT NULL,total REAL NOT NULL,sold_by INTEGER NOT NULL,sold_by_name TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT(datetime('now')));
CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,business_id INTEGER NOT NULL,description TEXT NOT NULL,amount REAL NOT NULL,created_by INTEGER NOT NULL,created_by_name TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT(datetime('now')));
CREATE TABLE IF NOT EXISTS debts(id INTEGER PRIMARY KEY AUTOINCREMENT,business_id INTEGER NOT NULL,person_name TEXT NOT NULL,description TEXT,amount REAL NOT NULL,status TEXT NOT NULL DEFAULT 'unpaid',created_by INTEGER NOT NULL,created_by_name TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT(datetime('now')));`);
try { db.exec("ALTER TABLE users ADD COLUMN phone TEXT"); } catch {}
try { db.exec("ALTER TABLE businesses ADD COLUMN location TEXT"); } catch {}
function hash(p){const s=crypto.randomBytes(16).toString('hex');return s+':'+crypto.scryptSync(p,s,64).toString('hex')}
function verify(p,x){try{const [s,h]=x.split(':');const c=crypto.scryptSync(p,s,64);return crypto.timingSafeEqual(Buffer.from(h,'hex'),c)}catch{return false}}
function code(){const c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let a=0;a<30;a++){let x='';for(let i=0;i<6;i++)x+=c[crypto.randomInt(c.length)];if(!db.prepare('SELECT 1 FROM businesses WHERE code=?').get(x))return x}throw Error('code')}
function seedOwner(){const email=(process.env.SUPER_ADMIN_EMAIL||'owner@daftariplus.com').trim().toLowerCase(),pw=process.env.SUPER_ADMIN_PASSWORD||'DaftariPlus@2026';let u=db.prepare("SELECT id FROM users WHERE email=? AND role='super_admin'").get(email);if(!u){db.prepare('INSERT INTO users(full_name,business_id,email,password_hash,role) VALUES(?,?,?,?,?)').run('Daftari Plus Owner',0,email,hash(pw),'super_admin')}}seedOwner();
function token(uid){const t=crypto.randomBytes(32).toString('hex'),e=new Date(Date.now()+1000*60*60*24*30).toISOString();db.prepare('INSERT INTO sessions VALUES(?,?,?,datetime(\'now\'))').run(t,uid,e);return t}
function user(req){const h=req.headers.authorization||'',m=h.match(/^Bearer (.+)$/);if(!m)return null;const s=db.prepare('SELECT * FROM sessions WHERE token=?').get(m[1]);if(!s||new Date(s.expires_at)<new Date()){if(s)db.prepare('DELETE FROM sessions WHERE token=?').run(m[1]);return null}return db.prepare('SELECT id,full_name,phone,business_id,email,role FROM users WHERE id=?').get(s.user_id)}
function auth(req,res,role){const u=user(req);if(!u){json(res,401,{error:'Haujaingia.'});return null}if(role&&u.role!==role){json(res,403,{error:'Ruhusa haitoshi.'});return null}return u}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS'});res.end(JSON.stringify(data))}
function body(req){return new Promise((ok,bad)=>{let d='';req.on('data',c=>{d+=c;if(d.length>2e6)req.destroy()});req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){bad(e)}});req.on('error',bad)})}
function q(req){const u=new URL(req.url,'http://x');return Object.fromEntries(u.searchParams.entries())}
function range(q){let f=q.from,t=q.to;if(q.period){const n=new Date(), d=new Date(n); if(q.period==='day')d.setHours(0,0,0,0);if(q.period==='week'){d.setDate(d.getDate()-((d.getDay()+6)%7));d.setHours(0,0,0,0)}if(q.period==='month')d.setDate(1);if(q.period==='3m')d.setMonth(d.getMonth()-2,d.getDate()||1),d.setDate(1);if(q.period==='6m')d.setMonth(d.getMonth()-5,d.getDate()||1),d.setDate(1);if(q.period==='year')d.setMonth(0,1),d.setHours(0,0,0,0);f=d.toISOString().slice(0,10);t=n.toISOString().slice(0,10)}if(q.year){f=q.year+'-01-01';t=q.year+'-12-31'}return [f?f+' 00:00:00':'1970-01-01 00:00:00',t?t+' 23:59:59':'2999-12-31 23:59:59']}
function dashboard(req,res){const u=auth(req,res);if(!u)return;if(u.role==='super_admin')return superDash(res);const b=u.business_id;const s=db.prepare('SELECT COUNT(*) count,COALESCE(SUM(total),0) revenue,COALESCE(SUM((sell_price-buy_price)*quantity),0) gross FROM sales WHERE business_id=?').get(b);const e=db.prepare('SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE business_id=?').get(b);const d=db.prepare("SELECT COALESCE(SUM(amount),0) total FROM debts WHERE business_id=? AND status='unpaid'").get(b);const p=db.prepare('SELECT COUNT(*) count FROM products WHERE business_id=?').get(b);json(res,200,{summary:{totalSales:s.count,totalRevenue:s.revenue,totalCost:s.revenue-s.gross,totalExpenses:e.total,totalDebts:d.total,totalProfit:s.gross-e.total,productCount:p.count,lowStock:db.prepare('SELECT id,name,quantity FROM products WHERE business_id=? AND quantity<=5 ORDER BY quantity').all(b)}})}
function superDash(res){const b=db.prepare('SELECT COUNT(*) count,SUM(status="active") active,SUM(status="suspended") suspended FROM businesses').get();const u=db.prepare("SELECT COUNT(*) count FROM users WHERE role!='super_admin'").get();const s=db.prepare('SELECT COUNT(*) count,COALESCE(SUM(total),0) revenue FROM sales').get();json(res,200,{summary:{businesses:b.count||0,activeBusinesses:b.active||0,suspendedBusinesses:b.suspended||0,users:u.count||0,totalSales:s.count,totalRevenue:s.revenue}})}
function reports(req,res){const u=auth(req,res);if(!u)return;if(u.role==='super_admin')return json(res,403,{error:'Tumia Super Admin panel kwa ripoti za jumla.'});const [f,t]=range(q(req));const sales=db.prepare('SELECT created_at,product_name,quantity,total,(sell_price-buy_price)*quantity profit,sold_by_name FROM sales WHERE business_id=? AND created_at BETWEEN ? AND ? ORDER BY created_at').all(u.business_id,f,t);const expenses=db.prepare('SELECT created_at,amount FROM expenses WHERE business_id=? AND created_at BETWEEN ? AND ?').all(u.business_id,f,t);const rev=sales.reduce((a,x)=>a+x.total,0),gross=sales.reduce((a,x)=>a+x.profit,0),exp=expenses.reduce((a,x)=>a+x.amount,0);json(res,200,{from:f,to:t,sales,expenses,summary:{revenue:rev,grossProfit:gross,expenses:exp,profit:gross-exp,margin:rev?((gross-exp)/rev*100):0}})}
function superBusinesses(req,res){const u=auth(req,res,'super_admin');if(!u)return;const rows=db.prepare(`SELECT b.id,b.name,b.code,b.status,b.created_at,u.full_name owner,(SELECT COUNT(*) FROM users x WHERE x.business_id=b.id) users,(SELECT COUNT(*) FROM sales s WHERE s.business_id=b.id) sales,(SELECT COALESCE(SUM(s.total),0) FROM sales s WHERE s.business_id=b.id) revenue FROM businesses b LEFT JOIN users u ON u.id=b.owner_id GROUP BY b.id ORDER BY b.created_at DESC`).all();json(res,200,{businesses:rows})}
function superUsers(req,res){const u=auth(req,res,'super_admin');if(!u)return;json(res,200,{users:db.prepare(`SELECT u.id,u.full_name,u.email,u.role,u.created_at,b.name business_name,b.status FROM users u LEFT JOIN businesses b ON b.id=u.business_id WHERE u.role!='super_admin' ORDER BY u.created_at DESC`).all()})}
function superPerf(req,res){const u=auth(req,res,'super_admin');if(!u)return;json(res,200,{performance:db.prepare(`SELECT b.id,b.name,b.status,COUNT(s.id) sales,COALESCE(SUM(s.total),0) revenue,COALESCE(SUM((s.sell_price-s.buy_price)*s.quantity),0) gross_profit,(SELECT COALESCE(SUM(amount),0) FROM expenses e WHERE e.business_id=b.id) expenses FROM businesses b LEFT JOIN sales s ON s.business_id=b.id GROUP BY b.id ORDER BY revenue DESC`).all()})}
function serve(req,res){let p=req.url.split('?')[0];if(p==='/')p='/index.html';const fp=path.join(ROOT,'public',p);if(!fp.startsWith(path.join(ROOT,'public')))return res.writeHead(403).end();fs.readFile(fp,(e,c)=>{if(e)return res.writeHead(404).end('Not found');const ext=path.extname(fp),m={'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':m[ext]||'application/octet-stream'});res.end(c)})}
async function api(req,res){const p=req.url.split('?')[0],method=req.method;if(method==='OPTIONS')return json(res,204,{});
if(p==='/api/login'&&method==='POST'){const x=await body(req);const e=(x.email||'').trim().toLowerCase(),pw=x.password||'',u=db.prepare('SELECT * FROM users WHERE email=?').get(e);if(!u||!verify(pw,u.password_hash))return json(res,401,{error:'Email au password si sahihi.'});if(u.role!=='super_admin'&&db.prepare('SELECT status FROM businesses WHERE id=?').get(u.business_id)?.status==='suspended')return json(res,403,{error:'Biashara imesimamishwa.'});return json(res,200,{token:token(u.id),user:{id:u.id,full_name:u.full_name,phone:u.phone,email:u.email,role:u.role,business_id:u.business_id}})}
if(p==='/api/register'&&method==='POST'){
  const x=await body(req),
        name=(x.fullName||'').trim(),
        phone=(x.phone||'').trim(),
        email=(x.email||'').trim().toLowerCase(),
        pw=x.password||'',
        role=x.role==='saler'?'saler':'admin';
  if(!name||!phone||!email||pw.length<8)return json(res,400,{error:'Jina, namba ya simu, email na password (min 8) vinahitajika.'});
  if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return json(res,409,{error:'Email hii tayari imesajiliwa.'});
  let bid;
  if(role==='admin'){
    const bn=(x.businessName||'').trim();
    const bloc=(x.businessLocation||'').trim();
    if(!bn)return json(res,400,{error:'Jina la biashara linahitajika.'});
    if(!bloc)return json(res,400,{error:'Mahali biashara ilipo panahitajika.'});
    const c=code(),br=db.prepare('INSERT INTO businesses(name,code,location) VALUES(?,?,?)').run(bn,c,bloc);
    bid=Number(br.lastInsertRowid);
  }else{
    const bc=(x.businessCode||'').trim().toUpperCase();
    if(!bc)return json(res,400,{error:'Business Code inahitajika kwa Muuzaji.'});
    const biz=db.prepare('SELECT id,status FROM businesses WHERE code=?').get(bc);
    if(!biz)return json(res,404,{error:'Business Code hii haipo. Uliza Admin wako.'});
    if(biz.status==='suspended')return json(res,403,{error:'Biashara hii imesimamishwa.'});
    bid=biz.id;
  }
  const ur=db.prepare('INSERT INTO users(full_name,phone,business_id,email,password_hash,role) VALUES(?,?,?,?,?,?)').run(name,phone,bid,email,hash(pw),role);
  const uid=Number(ur.lastInsertRowid);
  if(role==='admin')db.prepare('UPDATE businesses SET owner_id=? WHERE id=?').run(uid,bid);
  const biz2=db.prepare('SELECT name,code,location FROM businesses WHERE id=?').get(bid);
  return json(res,201,{token:token(uid),user:{id:uid,full_name:name,phone,email,role,business_id:bid},business:biz2});
}
if(p==='/api/me'){const u=auth(req,res);if(!u)return;return json(res,200,{user:u,business:u.role==='super_admin'?null:db.prepare('SELECT name,code,status,location FROM businesses WHERE id=?').get(u.business_id)})}
if(p==='/api/logout'){const h=req.headers.authorization||'',m=h.match(/^Bearer (.+)$/);if(m)db.prepare('DELETE FROM sessions WHERE token=?').run(m[1]);return json(res,200,{ok:true})}
if(p==='/api/dashboard')return dashboard(req,res);if(p==='/api/reports')return reports(req,res);
if(p==='/api/products'&&method==='GET'){const u=auth(req,res);if(!u)return;return json(res,200,{products:db.prepare('SELECT id,name,sell_price,quantity,buy_price FROM products WHERE business_id=? ORDER BY name').all(u.business_id)})}
if(p==='/api/products'&&method==='POST'){const u=auth(req,res,'admin');if(!u)return;const x=await body(req);const name=String(x.name||'').trim(),buy=Number(x.buyPrice),sell=Number(x.sellPrice),qty=Number.isFinite(Number(x.quantity))?Number(x.quantity):0;if(!name||!Number.isFinite(buy)||!Number.isFinite(sell))return json(res,400,{error:'Jina na bei vinahitajika.'});const r=db.prepare('INSERT INTO products(business_id,name,buy_price,sell_price,quantity) VALUES(?,?,?,?,?)').run(u.business_id,name,buy,sell,qty);return json(res,201,{product:{id:Number(r.lastInsertRowid)}})}
if(p==='/api/sales'&&method==='GET'){const u=auth(req,res);if(!u)return;return json(res,200,{sales:db.prepare('SELECT * FROM sales WHERE business_id=? ORDER BY created_at DESC LIMIT 500').all(u.business_id)})}
if(p==='/api/sales'&&method==='POST'){const u=auth(req,res);if(!u)return;const x=await body(req),pid=Number(x.productId),qty=Number(x.quantity),pdt=db.prepare('SELECT * FROM products WHERE id=? AND business_id=?').get(pid,u.business_id);if(!pdt||qty<=0||pdt.quantity<qty)return json(res,400,{error:'Bidhaa/idadi si sahihi au stock haitoshi.'});const total=pdt.sell_price*qty;db.prepare('UPDATE products SET quantity=quantity-? WHERE id=?').run(qty,pid);const r=db.prepare('INSERT INTO sales(business_id,product_id,product_name,quantity,sell_price,buy_price,total,sold_by,sold_by_name) VALUES(?,?,?,?,?,?,?,?,?)').run(u.business_id,pid,pdt.name,qty,pdt.sell_price,pdt.buy_price,total,u.id,u.full_name);return json(res,201,{sale:{id:Number(r.lastInsertRowid)}})}
if(p==='/api/expenses'&&method==='GET'){const u=auth(req,res);if(!u)return;return json(res,200,{expenses:db.prepare('SELECT * FROM expenses WHERE business_id=? ORDER BY created_at DESC LIMIT 500').all(u.business_id)})}
if(p==='/api/expenses'&&method==='POST'){const u=auth(req,res);if(!u)return;const x=await body(req),desc=String(x.description||'').trim(),amt=Number(x.amount);if(!desc||!Number.isFinite(amt)||amt<=0)return json(res,400,{error:'Maelezo na kiasi sahihi vinahitajika.'});db.prepare('INSERT INTO expenses(business_id,description,amount,created_by,created_by_name) VALUES(?,?,?,?,?)').run(u.business_id,desc,amt,u.id,u.full_name);return json(res,201,{ok:true})}
if(p==='/api/debts'&&method==='GET'){const u=auth(req,res);if(!u)return;return json(res,200,{debts:db.prepare('SELECT * FROM debts WHERE business_id=? ORDER BY created_at DESC LIMIT 500').all(u.business_id)})}
if(p==='/api/debts'&&method==='POST'){const u=auth(req,res);if(!u)return;const x=await body(req),person=String(x.personName||'').trim(),amt=Number(x.amount);if(!person||!Number.isFinite(amt)||amt<=0)return json(res,400,{error:'Jina la mtu na kiasi sahihi vinahitajika.'});db.prepare('INSERT INTO debts(business_id,person_name,description,amount,created_by,created_by_name) VALUES(?,?,?,?,?,?)').run(u.business_id,person,(x.description||'').trim()||null,amt,u.id,u.full_name);return json(res,201,{ok:true})}
let m=p.match(/^\/api\/debts\/(\d+)$/);if(m&&method==='PUT'){const u=auth(req,res);if(!u)return;db.prepare('UPDATE debts SET status=? WHERE id=? AND business_id=?').run((await body(req)).status==='paid'?'paid':'unpaid',Number(m[1]),u.business_id);return json(res,200,{ok:true})}
if(p==='/api/super/businesses')return superBusinesses(req,res);if(p==='/api/super/users')return superUsers(req,res);if(p==='/api/super/performance')return superPerf(req,res);
m=p.match(/^\/api\/super\/businesses\/(\d+)\/(suspend|activate)$/);if(m&&method==='PUT'){const u=auth(req,res,'super_admin');if(!u)return;db.prepare('UPDATE businesses SET status=? WHERE id=?').run(m[2]==='suspend'?'suspended':'active',Number(m[1]));return json(res,200,{ok:true})}
return json(res,404,{error:'Not found'})}
http.createServer((req,res)=>{if(req.url.startsWith('/api/'))api(req,res).catch(e=>json(res,500,{error:e.message}));else serve(req,res)}).listen(PORT,()=>console.log(`Daftari Plus SaaS: http://localhost:${PORT}`));

